config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get  '/about',     to: 'pages#about'

  get  '/eagle1040', to: 'pages#income_tax_service'

  get  '/team',      to: 'pages#team'

  get  '/coverage',  to: 'pages#coverage'

  get  '/blog',      to: 'pages#blog'

  get  '/contact',   to: 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def income_tax_service
  end

  def team
  end

  def coverage
  end

  def blog
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="navbar-static-bottom">
  <div id="copyright">
    <p>Jon Corrin ©2017</p>
    <%= link_to "Privacy", "#" %>
    <%= link_to "Terms", "#" %>
    <%= link_to "All of the links on the page down here for easy access", "#" %>
  </div>
</div>

app/views/layouts/_header.html.erb
<link rel="manifest" href="manifest.json">

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta charset="utf-8">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="application-name" content="A to Z">
<meta name="apple-mobile-web-app-title" content="A to Z">
<meta name="theme-color" content="#efefef">
<meta name="msapplication-navbutton-color" content="#efefef">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="msapplication-starturl" content="https://eagle1040.herokuapp.com/">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="icon" type="png" sizes="192x192" href="https://s3-us-west-2.amazonaws.com/joncorrin/logo-small.png">
<link rel="apple-touch-icon" type="png" sizes="192x192" href="https://s3-us-west-2.amazonaws.com/joncorrin/logo-small.png">
<link rel="icon" type="png" sizes="80x80" href="https://s3-us-west-2.amazonaws.com/joncorrin/logo-small.png">
<link rel="apple-touch-icon" type="png" sizes="80x80" href="https://s3-us-west-2.amazonaws.com/joncorrin/logo-small.png">
<link rel="icon" type="png" sizes="40x40" href="https://s3-us-west-2.amazonaws.com/joncorrin/logo-small.png">
<link rel="apple-touch-icon" type="png" sizes="40x40" href="https://s3-us-west-2.amazonaws.com/joncorrin/logo-small.png">
<link rel="icon" type="png" sizes="120x120" href="https://s3-us-west-2.amazonaws.com/joncorrin/logo-small.png">
<link rel="apple-touch-icon" type="png" sizes="120x120" href="https://s3-us-west-2.amazonaws.com/joncorrin/logo-small.png">
<link rel="icon" type="png" sizes="10x10" href="https://s3-us-west-2.amazonaws.com/joncorrin/logo-small.png">
<link rel="apple-touch-icon" type="png" sizes="10x10" href="https://s3-us-west-2.amazonaws.com/joncorrin/logo-small.png">
<link rel="icon" href="../../favicon.ico">

<title>A to Z Insurance</title>
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_homespanish.html.erb
<div class="spanish">
  <div class="container marketing">
    <div class="row">
      <div class="col-lg-4">
        <span class="fa-stack fa-5x" aria-hidden="true">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-home fa-stack-1x fa-inverse"></i>
        </span>
        <h2>Seguro del Propietario</h2>
        <p>EspanolEspanolEspanolEspanol. <br>EspanolEspanolEspanolEspanolEspanol
           EspanolEspanolEspanolEspanolEspanolEspanol<br>EspanolEspanolEspanol
           EspanolEspanolEspanol<br>EspanolEspanolEspanolEspanolEspanolEspanol</p>
        <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-lg-4">
        <span class="fa-stack fa-5x" aria-hidden="true">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-car fa-stack-1x fa-inverse"></i>
        </span>
        <h2>Seguro de automóvil</h2>
        <p>EspanolEspanolEspanolEspanol. <br>EspanolEspanolEspanolEspanolEspanol
           EspanolEspanolEspanolEspanolEspanolEspanol<br>EspanolEspanolEspanol
           EspanolEspanolEspanol<br>EspanolEspanolEspanolEspanolEspanolEspanol</p>
        <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      </div>
      <div class="col-lg-4">
        <span class="fa-stack fa-5x" aria-hidden="true">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-users fa-stack-1x fa-inverse"></i>
        </span>
        <h2>Seguro de vida</h2>
        <p>EspanolEspanolEspanolEspanol. <br>EspanolEspanolEspanolEspanolEspanol
           EspanolEspanolEspanolEspanolEspanolEspanol<br>EspanolEspanolEspanol
           EspanolEspanolEspanol<br>EspanolEspanolEspanolEspanolEspanolEspanol</p>
        <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      </div>
    </div>


  <!-- START THE FEATURETTES -->

  <hr class="featurette-divider">

  <div class="colored-featurette">
    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">Primero, nuestro equipo. <span class="text-muted">Te volaremos la cabeza.</span></h2>
        <p class="lead">EspanolEspanolEspanolEspanol. <br>EspanolEspanolEspanolEspanolEspanol
           EspanolEspanolEspanolEspanolEspanolEspanol<br>EspanolEspanolEspanol
           EspanolEspanolEspanol<br>EspanolEspanolEspanolEspanolEspanolEspanol</p>
      </div>
      <div class="col-md-5">
        <%= image_tag "working.jpg", class:"featurette-image img-responsive center-block", alt:"People working" %>
      </div>
    </div>
  </div>

  <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 col-md-push-5">
        <h2 class="featurette-heading">Oh, sí, somos amigables. <span class="text-muted">Ver por ti mismo.</span></h2>
        <p class="lead">EspanolEspanolEspanolEspanol. <br>EspanolEspanolEspanolEspanolEspanol
           EspanolEspanolEspanolEspanolEspanolEspanol<br>EspanolEspanolEspanol
           EspanolEspanolEspanol<br>EspanolEspanolEspanolEspanolEspanolEspanol</p>
      </div>
      <div class="col-md-5 col-md-pull-7">
        <%= image_tag "service.jpg", class:"featurette-image img-responsive center-block", alt:"Customer service" %>
      </div>
    </div>

  <hr class="featurette-divider">
  <div class="colored-featurette">
    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">Obtenga una cotización tan fácilmente. <span class="text-muted">Mate.</span></h2>
        <p class="lead">EspanolEspanolEspanolEspanol. <br>EspanolEspanolEspanolEspanolEspanol
           EspanolEspanolEspanolEspanolEspanolEspanol<br>EspanolEspanolEspanol
           EspanolEspanolEspanol<br>EspanolEspanolEspanolEspanolEspanolEspanol</p>
      </div>
      <div class="col-md-5">
        <%= image_tag "customer.jpg", class:"featurette-image img-responsive center-block", alt:"Customer" %>
      </div>
    </div>
  </div>

  <hr class="featurette-divider">
  </div><!-- /.container -->
</div>

app/views/layouts/_navbars.html.erb
<div class="navbar-wrapper">
  <div class="container">

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                  data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "A to Z Insurance", root_path, class:"navbar-brand" %>
        </div>
        <div class="english">
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "About", about_path, class:"btn btn-link" %></li>
              <li><%= link_to "Contact", contact_path, class:"btn btn-link" %></li>
              <li><%= link_to "Eagle1040", eagle1040_path, class:"btn btn-link" %></li>
              <li><%= link_to "Team", team_path, class:"btn btn-link" %></li>
              <li><%= link_to "Coverage", coverage_path, class:"btn btn-link" %></li>
              <li><%= link_to "Blog", blog_path, class:"btn btn-link" %></li>
              <li><%= link_to "1-888-721-2511", "tel:+18887212511", id:"calldigits", class:"btn btn-link" %></li>
              <li class="btn btn-link"><button class="translator", style="margin-top: 9px;
                                 vertical-align: middle; text-align: center !important;">En español</button></li>
            </ul>
            <div class= "nav navbar-right">
              <ul class="nav navbar-nav">
                <!--<li><%= button_to "GET A QUOTE", "#", class:"btn btn-success" %></li>-->
              </ul>
            </div>
          </div>
        </div>
        <div class="spanish">
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Nosotros", about_path, class:"btn btn-link" %></li>
              <li><%= link_to "Contáctenos", contact_path, class:"btn btn-link" %></li>
              <li><%= link_to "Eagle1040", eagle1040_path, class:"btn btn-link" %></li>
              <li><%= link_to "Equipo", team_path, class:"btn btn-link" %></li>
              <li><%= link_to "Cobertura", coverage_path, class:"btn btn-link" %></li>
              <li><%= link_to "Blog", blog_path, class:"btn btn-link" %></li>
            </ul>
            <div class= "nav navbar-right">
              <ul class="nav navbar-nav">
                <!--<li><%= button_to "Cotización", "#", class:"btn btn-success" %></li>-->
                <li><%= link_to "1-888-721-2511", "tel:+18887212511", class:"btn btn-link", id:"calldigits", style:"font-size: 25px !important;" %></li>
                <li class="btn btn-link"><button class="translator", style="margin-top: 9px;
                                   vertical-align: middle; text-align: center !important;">In English</button></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/header' %>
  </head>

  <body>
    <%= render 'layouts/navbars' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/blog.html.erb
<h1>Pages#blog</h1>
<p>Find me in app/views/pages/blog.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/coverage.html.erb
<h1>Pages#coverage</h1>
<p>Find me in app/views/pages/coverage.html.erb</p>

app/views/pages/home.html.erb
<!-- Carousel
================================================== -->
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-caption" style="margin-bottom: 100px;">
        <div class="english">
          <h1><strong>Life starts with A to Z</strong></h1>
          <h3>Click for a quote now!</h3>
          <%= button_to "QUOTE", "#", class:"btn btn-success btn-lg" %>
        </div>
        <div class="spanish">
          <h1><strong>La vida comienza con A to Z</strong></h1>
          <h3>Haga clic para una cita ahora!</h3>
          <%= button_to "Cotización", "#", class:"btn btn-success btn-lg" %>
        </div>
      </div>
      <div class="overlay">
      </div>
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img class="first-slide" alt="First slide">
        <div class="container">
        </div>
      </div>
      <div class="item">
        <img class="second-slide" alt="Second slide">
        <div class="container">
        </div>
      </div>
      <div class="item">
        <img class="third-slide" alt="Third slide">
        <div class="container">
        </div>
      </div>
    </div>
  </div><!-- /.carousel -->

<!--Features and marketing calls--------------------->
<div class="english">
    <div class="container marketing">
      <div class="row">
        <div class="col-lg-4">
          <span class="fa-stack fa-5x" aria-hidden="true">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-home fa-stack-1x fa-inverse"></i>
          </span>
          <h2>Homeowner's and Renter's Insurance</h2>
          <p>English paragraph English paragraph English paragraph English paragraph
             English paragraph English paragraph English paragraph English paragraph English paragraph English paragraph.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-lg-4">
          <span class="fa-stack fa-5x" aria-hidden="true">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-car fa-stack-1x fa-inverse"></i>
          </span>
          <h2>Auto, Motorcycle, Truck and RV Insurance</h2>
          <p>English paragraph English paragraph English paragraph English paragraph
             English paragraph English paragraph English paragraph English paragraph English paragraph
             English paragraph English paragraph English paragraph</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-lg-4">
          <span class="fa-stack fa-5x" aria-hidden="true">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-users fa-stack-1x fa-inverse"></i>
          </span>
          <h2>Life, Health, and Supplemental Insurance</h2>
          <p>English paragraph English paragraph English paragraph English paragraph
             English paragraph English paragraph English paragraph English paragraph
             English paragraph English paragraph English paragraph English paragraph English paragraph English paragraph</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="colored-featurette">
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">First off, our team. <span class="text-muted">We'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper.
                          Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <%= image_tag ("working.jpg"), class:"featurette-image img-responsive center-block", alt:"People working" %>
        </div>
      </div>
    </div>

    <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Oh yeah, we're friendly. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper.
                          Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <%= image_tag "service.jpg", class:"featurette-image img-responsive center-block", alt:"Customer service" %>
        </div>
      </div>

    <hr class="featurette-divider">
    <div class="colored-featurette">
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Get a quote so easily. <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper.
                          Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <%= image_tag "customer.jpg", class:"featurette-image img-responsive center-block", alt:"Customer" %>
        </div>
      </div>
    </div>

    <hr class="featurette-divider">
  </div><!-- /.container -->
</div>
<%= render 'layouts/homespanish' %>

app/views/pages/income_tax_service.html.erb
<h1>Pages#income_tax_service</h1>
<p>Find me in app/views/pages/income_tax_service.html.erb</p>

app/views/pages/team.html.erb
<h1>Pages#team</h1>
<p>Find me in app/views/pages/team.html.erb</p>